### ISSUE TITLE
Still seeing suggested posts with extension turned on

### ISSUE THREAD

**Issue by cdavid** [mohamedmansour/fblock#1]
Hi

I loaded the extension in Chrome, but I still get the suggested posts (see screenshot below). I don't believe that uBlock Origin or Ghostery and I can see in the Console that it says "Remove sponsored post #1" and #2, so I think that something else might be going on.

![image](https://cloud.githubusercontent.com/assets/395543/17544786/3eed7714-5e8e-11e6-8106-97063d0c3942.png)

**Comment by mohamedmansour** [comment]
I think I know the problem, I will update it soon

**Comment by mohamedmansour** [comment]
What I fixed in above commit is that there was a bug recognizing what the parent was, and dynamic sidebar loading wasn't done. I submitted a fix and updated the app in the Chrome Store. Thanks for your feedback @cdavid

**Comment by cdavid** [comment]
Awesome, works now.
